import type { Project, Task } from "./project-types"

export const INITIAL_PROJECTS: Project[] = [
  {
    id: "p1",
    name: "智慧养老App",
    type: "IT开发",
    lastModified: "12/26 14:30",
    workflow: {
      nodes: [
        {
          id: "root",
          type: "member",
          label: "需求分析",
          assignee: "萧祷(队长)",
          status: "已完成",
          deadline: "2024-01-15",
          x: 50,
          y: 200,
        },
        {
          id: "ui-design",
          type: "member",
          label: "UI 设计",
          assignee: "一墨乾行",
          status: "进行中",
          deadline: "2024-02-01",
          x: 350,
          y: 100,
        },
        {
          id: "backend",
          type: "member",
          label: "后端开发",
          assignee: "Fine",
          status: "进行中",
          deadline: "2024-02-05",
          x: 350,
          y: 300,
        },
        {
          id: "frontend",
          type: "member",
          label: "前端对接",
          assignee: "一墨乾行",
          status: "待办",
          deadline: "2024-02-10",
          x: 650,
          y: 200,
        },
        {
          id: "testing",
          type: "member",
          label: "测试交付",
          assignee: "萧祷(队长)",
          status: "待办",
          deadline: "2024-02-20",
          x: 950,
          y: 200,
        },
      ],
      edges: [
        { id: "e1", source: "root", target: "ui-design", sourceHandle: "right", targetHandle: "left" },
        { id: "e2", source: "root", target: "backend", sourceHandle: "right", targetHandle: "left" },
        { id: "e3", source: "ui-design", target: "frontend", sourceHandle: "right", targetHandle: "left" },
        { id: "e4", source: "backend", target: "frontend", sourceHandle: "right", targetHandle: "left" },
        { id: "e5", source: "frontend", target: "testing", sourceHandle: "right", targetHandle: "left" },
      ],
    },
  },
  {
    id: "p2",
    name: "近代史汇报",
    type: "人文报告",
    lastModified: "12/25 10:15",
    workflow: {
      nodes: [
        {
          id: "topic",
          type: "member",
          label: "选题：洋务运动成败分析",
          assignee: "萧祷(队长)",
          status: "已完成",
          deadline: "2024-01-10",
          x: 50,
          y: 200,
        },
        {
          id: "materials",
          type: "member",
          label: "史料搜集",
          assignee: "萧祷(队长)",
          status: "进行中",
          deadline: "2024-01-20",
          x: 350,
          y: 100,
        },
        {
          id: "archive",
          type: "member",
          label: "原始档案筛选",
          assignee: "一墨乾行",
          status: "待办",
          deadline: "2024-01-25",
          x: 650,
          y: 100,
        },
        {
          id: "review",
          type: "ai",
          label: "小耶：学术回顾",
          status: "进行中",
          x: 350,
          y: 300,
        },
        {
          id: "analysis",
          type: "member",
          label: "观点提炼",
          assignee: "Fine",
          status: "待办",
          deadline: "2024-01-28",
          x: 650,
          y: 300,
        },
        {
          id: "writing",
          type: "member",
          label: "报告撰写 & 格式统一",
          assignee: "萧祷(队长)",
          status: "待办",
          deadline: "2024-02-05",
          x: 950,
          y: 200,
        },
        {
          id: "ppt",
          type: "ai",
          label: "小耶：PPT 生成",
          status: "待办",
          x: 1250,
          y: 200,
        },
      ],
      edges: [
        { id: "e1", source: "topic", target: "materials", sourceHandle: "right", targetHandle: "left" },
        { id: "e2", source: "topic", target: "review", sourceHandle: "right", targetHandle: "left" },
        { id: "e3", source: "materials", target: "archive", sourceHandle: "right", targetHandle: "left" },
        { id: "e4", source: "review", target: "analysis", sourceHandle: "right", targetHandle: "left" },
        { id: "e5", source: "archive", target: "writing", sourceHandle: "right", targetHandle: "left" },
        { id: "e6", source: "analysis", target: "writing", sourceHandle: "right", targetHandle: "left" },
        { id: "e7", source: "writing", target: "ppt", sourceHandle: "right", targetHandle: "left" },
      ],
    },
  },
  {
    id: "p3",
    name: "营销分析",
    type: "商业分析",
    lastModified: "12/24 16:45",
    workflow: {
      nodes: [
        {
          id: "kickoff",
          type: "member",
          label: "项目启动：竞品分析",
          assignee: "萧祷(队长)",
          status: "已完成",
          deadline: "2024-01-08",
          x: 50,
          y: 200,
        },
        {
          id: "swot",
          type: "ai",
          label: "小耶：SWOT 矩阵构建",
          status: "已完成",
          x: 350,
          y: 100,
        },
        {
          id: "survey",
          type: "member",
          label: "问卷数据清洗",
          assignee: "一墨乾行",
          status: "进行中",
          deadline: "2024-01-18",
          x: 350,
          y: 300,
        },
        {
          id: "visualization",
          type: "member",
          label: "可视化图表生成",
          assignee: "Fine",
          status: "待办",
          deadline: "2024-01-22",
          x: 650,
          y: 300,
        },
        {
          id: "bp",
          type: "member",
          label: "商业计划书 (BP) 撰写",
          assignee: "萧祷(队长)",
          status: "待办",
          deadline: "2024-02-01",
          x: 950,
          y: 200,
        },
        {
          id: "roadshow",
          type: "ai",
          label: "小耶：路演模拟",
          status: "待办",
          x: 1250,
          y: 200,
        },
      ],
      edges: [
        { id: "e1", source: "kickoff", target: "swot", sourceHandle: "right", targetHandle: "left" },
        { id: "e2", source: "kickoff", target: "survey", sourceHandle: "right", targetHandle: "left" },
        { id: "e3", source: "survey", target: "visualization", sourceHandle: "right", targetHandle: "left" },
        { id: "e4", source: "swot", target: "bp", sourceHandle: "right", targetHandle: "left" },
        { id: "e5", source: "visualization", target: "bp", sourceHandle: "right", targetHandle: "left" },
        { id: "e6", source: "bp", target: "roadshow", sourceHandle: "right", targetHandle: "left" },
      ],
    },
  },
]

// 用户任务数据
export const USER_TASKS: Task[] = [
  { id: "t1", title: "完成App原型设计", project: "智慧养老App", dueDate: "今天", messageCount: 2 },
  { id: "t2", title: "撰写需求文档", project: "智慧养老App", dueDate: "明天", messageCount: 0 },
  { id: "t3", title: "整理历史文献", project: "近代史汇报", dueDate: "后天", messageCount: 1 },
  { id: "t4", title: "制作SWOT分析图", project: "营销方案", dueDate: "本周", messageCount: 0 },
]

// 项目消息数量
export const PROJECT_MESSAGE_COUNTS: Record<string, number> = {
  p1: 3,
  p2: 1,
  p3: 5,
}

export const initialProjects = INITIAL_PROJECTS

